# Generated by Django 5.1.4 on 2024-12-14 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy_cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spycats',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Salary cant be negative')]),
        ),
        migrations.AlterField(
            model_name='spycats',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40, message='Cats don`t live so long(')]),
        ),
    ]
