version: '1'

services:
  django:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: csa_test_task
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "csa_test_task", "-h", "localhost", "-p", "5432", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:latest
    depends_on:
      - django